# -*- coding: utf-8 -*-
"""Copy of Stable Diffusion as a Service API

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hfCRnyyRsALIaErZFLPfv3phz-D1i8n3
"""

!pip install diffuzers -qqqq

!diffuzers api --help

#Environment Variable

# Commented out IPython magic to ensure Python compatibility.
# %env X2IMG_MODEL=stabilityai/stable-diffusion-2-1

# Commented out IPython magic to ensure Python compatibility.
# %env DEVICE=cuda

!diffuzers api --port 10000  & npx localtunnel --port 10000

